<?php

namespace ShopBundle\Repository;

/**
 * ProducteursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProducteursRepository extends \Doctrine\ORM\EntityRepository
{
}
